name: Generate Changelog
description: >
  Auto-generate a Keep a Changelog section from git history.
  Extracts PR numbers from squash-merge commits, fetches actual PR titles via
  the GitHub CLI, categorises them by conventional-commit prefix, updates
  CHANGELOG.md in-place, and outputs the release-notes markdown.

inputs:
  version:
    description: The new version number (e.g., 4.17.0)
    required: true
  repo-url:
    description: >
      GitHub repository URL for comparison links.
      Defaults to https://github.com/$GITHUB_REPOSITORY.
    required: false
    default: ""
  tag-prefix:
    description: >
      Prefix for git tags (e.g., "v"). Leave empty to auto-detect both
      v-prefixed and bare version tags.
    required: false
    default: ""
  changelog-path:
    description: Path to the CHANGELOG.md file to update
    required: false
    default: CHANGELOG.md
  exclude-types:
    description: >
      Comma-separated conventional-commit types to exclude from the changelog
      (e.g., "chore,ci,test,build"). Breaking changes are never excluded.
    required: false
    default: ""

outputs:
  release-notes:
    description: Generated changelog section (markdown)
    value: ${{ steps.generate.outputs.release-notes }}

runs:
  using: composite
  steps:
    - id: generate
      shell: bash
      run: python3 "${{ github.action_path }}/generate_changelog.py"
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_REPO_URL: ${{ inputs.repo-url }}
        INPUT_TAG_PREFIX: ${{ inputs.tag-prefix }}
        INPUT_CHANGELOG_PATH: ${{ inputs.changelog-path }}
        INPUT_EXCLUDE_TYPES: ${{ inputs.exclude-types }}
