name: Open Source Pull Request Opened

on:
  workflow_call:
    secrets:
      gchat_webhook:
        required: true
  pull_request:
    types: [opened]

jobs:
  notify-gchat:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Send Google Chat Notification for PR
        if: github.event_name == 'pull_request'
        uses: google-github-actions/send-google-chat-webhook@v0.0.4
        with:
          webhook_url: ${{ secrets.gchat_webhook }}
          title: PR Created - ${{ github.event.pull_request.title }}
          imageUrl: ${{ github.event.pull_request.user.avatar_url }}
